### ISSUE TITLE
Stub a func registered in some package's init()

### ISSUE THREAD

**Issue by TodLiuMeng** [prashantv/gostub#6]
hi I have a question here how to substitute a func in the init of some package.
One example:

package http
func AuthenticationFilter(ctx *context.Context) {
	....
}
func init() {
	beego.InsertFilter("/*", beego.BeforeExec, AuthenticationFilter)
}

I want to substitute AuthenticationFilter before the http package initialize. 
stubs.Stub(&http.AuthenticationFilter, func (ctx *context.Context) {
...
})
How should I do? Thx a lot

**Comment by prashantv** [comment]
Init functions will be run as packages are loaded. I'd suggest avoiding init functions to make testing possible.
